// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// CudaTest FFI bindings
class CudaTest {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  CudaTest(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  CudaTest.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void setD3D11DeviceForCuda(
    ffi.Pointer<ffi.Void> device,
  ) {
    return _setD3D11DeviceForCuda(
      device,
    );
  }

  late final _setD3D11DeviceForCudaPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'setD3D11DeviceForCuda');
  late final _setD3D11DeviceForCuda = _setD3D11DeviceForCudaPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
